name: CI Pipeline

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Use the latest version

      - name: Setup Node.js
        uses: actions/setup-node@v4 # Use the latest version
        with:
          node-version: '20' # Using LTS version 20 is common
          # cache: 'npm' # Enable caching for npm

      - name: Install Backend Dependencies
        working-directory: ./backend # Set working directory for this and subsequent steps
        run: npm install

      - name: Run Backend Linter
        working-directory: ./backend
        run: npm run lint # It's better to use an npm script

      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm install

      - name: Run Frontend Linter
        working-directory: ./frontend
        run: npm run lint
