name: CI Pipeline

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Backend Dependencies
        run: cd backend && npm install

      - name: Run Backend Linter
        run: cd backend && npx eslint .

      - name: Install Frontend Dependencies
        run: cd frontend && npm install

      - name: Run Frontend Linter
        run: cd frontend && npx eslint .